### ISSUE TITLE
blas/netlib: crash during Dgemv test

### ISSUE THREAD

**Issue by kortschak** [gonum/netlib#23]
Filed in case someone has an idea - this is from travis.

```
=== RUN   TestDgemv
SIGILL: illegal instruction
PC=0x7fc17ae571e2 m=0 sigcode=2
signal arrived during cgo execution

goroutine 18 [syscall, locked to thread]:
runtime.cgocall(0x550990, 0xc420045830, 0x18)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/cgocall.go:132 +0xe4 fp=0xc4200457c8 sp=0xc420045788 pc=0x407914
gonum.org/v1/netlib/blas/netlib._Cfunc_cblas_dgemv(0x7000000065, 0x500000003, 0x4020000000000000, 0xc42001d480, 0x5, 0xc42009a060, 0xc400000001, 0xc018000000000000, 0xc420019ad0, 0x1)
	gonum.org/v1/netlib/blas/netlib/_test/_obj_test/_cgo_gotypes.go:877 +0x45 fp=0xc420045830 sp=0xc4200457c8 pc=0x544dd5
gonum.org/v1/netlib/blas/netlib.Implementation.Dgemv(0x70, 0x3, 0x5, 0x4020000000000000, 0xc42001d480, 0xf, 0xf, 0x5, 0xc42009a060, 0x3, ...)
	/home/travis/gopath/src/gonum.org/v1/netlib/blas/netlib/blas.go:1789 +0x1b7 fp=0xc420045890 sp=0xc420045830 pc=0x549e97
gonum.org/v1/netlib/blas/netlib.(*Implementation).Dgemv(0x8c2cd8, 0x70, 0x3, 0x5, 0x4020000000000000, 0xc42001d480, 0xf, 0xf, 0x5, 0xc42009a060, ...)
	<autogenerated>:1 +0x135 fp=0xc420045928 sp=0xc420045890 pc=0x54e215
gonum.org/v1/gonum/blas/testblas.dgemvcomp.func1()
	/home/travis/gopath/src/gonum.org/v1/gonum/blas/testblas/dgemv.go:611 +0x13a fp=0xc4200459e8 sp=0xc420045928 pc=0x52d1da
gonum.org/v1/gonum/blas/testblas.panics(0xc420045bf8, 0x0)
	/home/travis/gopath/src/gonum.org/v1/gonum/blas/testblas/common.go:98 +0x52 fp=0xc420045a10 sp=0xc4200459e8 pc=0x4f6dc2
gonum.org/v1/gonum/blas/testblas.dgemvcomp(0xc42008ec30, 0x5ab730, 0x11, 0x3, 0x5, 0x883000, 0x3, 0x3, 0x70, 0x88d120, ...)
	/home/travis/gopath/src/gonum.org/v1/gonum/blas/testblas/dgemv.go:613 +0x341 fp=0xc420045cb8 sp=0xc420045a10 pc=0x4fab51
gonum.org/v1/gonum/blas/testblas.DgemvTest(0xc42008ec30, 0x88e9c0, 0x8c2cd8)
	/home/travis/gopath/src/gonum.org/v1/gonum/blas/testblas/dgemv.go:585 +0x13f fp=0xc420045f80 sp=0xc420045cb8 pc=0x4fa66f
gonum.org/v1/netlib/blas/netlib.TestDgemv(0xc42008ec30)
	/home/travis/gopath/src/gonum.org/v1/netlib/blas/netlib/level2double_test.go:14 +0x43 fp=0xc420045fa8 sp=0xc420045f80 pc=0x543933
testing.tRunner(0xc42008ec30, 0x5b4808)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0xd0 fp=0xc420045fd0 sp=0xc420045fa8 pc=0x4b8fb0
runtime.goexit()
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420045fd8 sp=0xc420045fd0 pc=0x45c601
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:789 +0x2de

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42008e000, 0x5a9c65, 0x9, 0x5b4808, 0x46e301)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc42008e000)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc42008e000, 0xc420057de0)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42000c100, 0x8867a0, 0x23, 0x23, 0x0)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420057f18, 0xc420057f70)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:921 +0x111
main.main()
	gonum.org/v1/netlib/blas/netlib/_test/_testmain.go:514 +0xdb

rax    0x4
rbx    0x8
rcx    0xc420019ad0
rdx    0xc42009a060
rdi    0x0
rsi    0xc42001d4a8
rbp    0x4
rsp    0x7ffe23db8308
r8     0x7ffe23db83d8
r9     0xc42001d480
r10    0x7ffe23db84a0
r11    0x3
r12    0xc42001d480
r13    0xc42009a070
r14    0x5
r15    0xa0
rip    0x7fc17ae571e2
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
FAIL	gonum.org/v1/netlib/blas/netlib	0.010s
```

**Comment by vladimir-ch** [comment]
I'm not sure we can get anything useful without knowing where exactly the sigill happened (a backtrace from inside OpenBLAS?), output from /proc/cpuinfo, and probably what cpu OpenBLAS detected? Searching OpenBLAS repo on Github for "dgemv sigill" gives two issues but they don't seem to be relevant for this case.

**Comment by kortschak** [comment]
Yes, this is more a data point than anything else. I think for other reasons in addition to this, it might be worth sending an experimental PR/commit with `cat /proc/cpuinfo` to get an idea of what the hardware being used by travis is - this may help us understand the occasional floating point issues we have.

**Comment by kortschak** [comment]
Here is a cpuinfo output. I'll leave the branch I used to get this up but not submitted to allow easy checks for this in the future; just rerun the test if needed.

```
$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms xsaveopt
bugs		:
bogomips	: 4600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms xsaveopt
bugs		:
bogomips	: 4600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Comment by kortschak** [comment]
I've never seen this since. So closing.
